// Europa Clipper mug explainer: glossary. GENERATED from PLAN.md section B by tools/page/gen_copy.py. Edit the plan, not this block.
// t = term, m = regex alternates that auto-link in the text (case-insensitive unless cs:1 on the term or a leading '=' on the pattern),
// d = ELI5 line (always shown), x = Engineer line (Engineer mode), src = source tags.
import { OWNER_NAME } from './content.js';

export const TERMS = {
  clipper: {"t": "Europa Clipper", "m": ["Europa Clipper", "Clipper"], "d": "NASA's spacecraft, launched in 2024, that will fly past Jupiter's moon Europa 49 times after it arrives at Jupiter in 2030, to find out whether it hides an ocean that could support life.", "x": "Launch 14 Oct 2024 on Falcon Heavy; JOI 11 Apr 2030; 49 Europa flybys at 25–100 km; nine instruments plus gravity/radio science; end of prime mission 23 Jun 2034.", "src": "NASA, C25, P24, JPL"},
  europa: {"t": "Europa", "m": ["Europa(?! Clipper)"], "d": "One of Jupiter's big moons. It is covered in ice, and scientists think a salty ocean lies under the ice.", "x": "Target of the 49 science flybys; the ocean's existence, depth and salinity and the ice-shell thickness are what ECM aims to measure.", "src": "NASA"},
  jupiter: {"t": "Jupiter", "m": ["Jupiter(?:'s)?"], "d": "The biggest planet. Clipper orbits Jupiter, not Europa, and dips past Europa on each lap.", "x": "Clipper enters Jupiter orbit on 11 Apr 2030 and tours with 49 Europa, 7 Ganymede and 9 Callisto flybys.", "src": "P24, JPL"},
  frame: {"t": "Body frame (X, Y, Z)", "m": ["body frame", "spacecraft frame", "frame"], "d": "Three arrows painted on the ship, X, Y and Z, used to say which way anything points. The mug is a map of them.", "x": "EUROPAM_SPACECRAFT (−159000): origin at the LV separation plane; +Y toward the nadir instruments; +Z along the LV centreline; +X completes the right-handed frame along the arrays.", "src": "FK"},
  nadir: {"t": "Nadir", "m": ["nadir"], "d": "Straight down at the moon. During a flyby the +Y side of the ship points nadir.", "x": "+Y is pointed nadir during Europa encounters so the remote-sensing apertures face the surface.", "src": "M23, FK"},
  ram: {"t": "Ram direction", "m": ["ram(?: direction)?"], "d": "The direction the ship is moving, the side that meets gas and dust head-on. At closest approach that is +Z.", "x": "+Z is the velocity direction at closest approach; MASPEX and SUDA point +Z. The nadir-ram twist happens before 40,000 km altitude.", "src": "FK, P24, C25"},
  antinadir: {"t": "Anti-nadir / anti-ram", "m": ["anti-nadir", "anti-ram"], "d": "The opposite of nadir (so −Y, away from the moon) and the opposite of ram (−Z, backward).", "x": "PIMS cup names: ANTI_NADIR (−Y) on Upper, ANTI_RAM (−Z) on Lower.", "src": "FK"},
  sca: {"t": "SCA configuration", "m": ["SCA", "standard closest approach"], "d": "The pose the ship holds for the lowest part of each flyby: +Y at the moon, +Z forward, solar wings turned so the radar edge faces down.", "x": "\"Standard closest approach (SCA) configuration\": arrays at the fixed −90° REASON position with the VHF/HF antenna edge toward nadir, adopted near 10,000 km.", "src": "C25"},
  ca: {"t": "Closest approach (C/A)", "m": ["closest approach", "C/A", "=\\bCA\\b"], "d": "The lowest point of a flyby, as low as 25 km above the ice.", "x": "Typical C/A distances 25–100 km; EIS designed for ∼4.5 km/s ground-track speed at 25 km. The FK diagrams write it \"@CA\", as in \"+Ysc and Nadir @CA\".", "src": "P24, T24, FK"},
  flyby: {"t": "Flyby", "m": ["flybys?", "swoop"], "d": "A fast pass close to a moon or planet without stopping to orbit it.", "x": "Flybys let the spacecraft dip into the radiation belt briefly and escape; the tour has 65 satellite flybys in all (49 + 7 + 9 [D]).", "src": "C25, JPL"},
  gravassist: {"t": "Gravity assist", "m": ["gravity assist", "gravity-assist", "borrow(?:ed|s)? speed"], "d": "Using a planet's pull as a slingshot to speed up for free.", "x": "Mars flyby 1 Mar 2025 at 884 km; Earth flyby Dec 2026 (exact date unconfirmed).", "src": "JPL"},
  joi: {"t": "Jupiter Orbit Insertion (JOI)", "m": ["JOI", "Jupiter Orbit Insertion"], "d": "The engine burn that slows the ship enough for Jupiter to capture it.", "x": "11 April 2030.", "src": "P24, JPL"},
  vault: {"t": "Vault (Avionics Module)", "m": ["vault", "avionics module"], "d": "A thick metal box that holds the ship's electronics and shields them from Jupiter's radiation.", "x": "Aluminium–zinc alloy walls up to 9.2 mm; the Avionics Module with thick sidewalls, floor and lid, stacked on the Propulsion Module; the nadir deck mounts to it.", "src": "JPL, S25"},
  propmod: {"t": "Propulsion module", "m": ["propulsion module", "fuel module"], "d": "The round tank section at the bottom (−Z) of the ship that holds fuel, the engines, the wheels and the magnetometer boom.", "x": "Aluminium cylinder about 3 m long and 1.5 m wide; carries the RF module, ECM, radiator, PIMS Lower, REASON antenna cabling and the reaction wheels; tanks hold about 2,750 kg of propellant.", "src": "NASA, P24, JPL"},
  nadirdeck: {"t": "Nadir deck", "m": ["nadir deck", "shelf"], "d": "The shelf on the +Y side where most of the cameras are mounted so they all look the same way.", "x": "A separate structure kinematically mounted to the vault for mechanical isolation; hosts UVS, EIS NAC/WAC and E-THEMIS; MISE mounts to the vault.", "src": "P24, S25"},
  lva: {"t": "Launch vehicle adapter (LVA)", "m": ["launch adapter", "LVA", "separation plane"], "d": "The ring at the −Z end where the ship sat on top of the rocket.", "x": "The X–Y plane of the body frame is the spacecraft–launch vehicle interface; the origin is the centre of the separation circle.", "src": "FK"},
  sa: {"t": "Solar array", "m": ["solar arrays?", "solar wings?", "wings?", "arrays?", "=\\bSA\\b"], "d": "The two long panels (+X and −X) that turn sunlight into electricity.", "x": "Five panels each, ≈ 14.2 m × 4.1 m, 102 m² total, span 30.5 m; 700 W at end of mission; single-axis articulated; cells face −Y at zero.", "src": "JPL, P24, FK"},
  pv: {"t": "PV side", "m": ["PV side", "PV"], "d": "The side of a solar wing with the cells on it (PV = photovoltaic).", "x": "At the zero position the cells face −Y (SA frame +Z co-aligned with −Y).", "src": "FK"},
  reason: {"t": "REASON", "m": ["REASON"], "d": "Radar for Europa Assessment and Sounding: Ocean to Near-surface. A radar on the wings that sees through ice.", "x": "Dual-frequency ice-penetrating radar, 9 and 60 MHz; antennas on the arrays: two 17.6 m HF dipoles and four 2.76 m VHF folded dipoles.", "src": "B24, NASA"},
  radar: {"t": "Radar sounding", "m": ["radar", "sounding", "echo(?:es)?"], "d": "Sending a radio ping and timing the echo to measure how far away things are, even through ice.", "x": "Echo delay gives range; two-way time in ice ≈ 2d·n/c (n ≈ 1.78, general physics).", "src": "general"},
  dipole: {"t": "Dipole antenna", "m": ["dipoles?", "folded dipole"], "d": "A straight rod antenna, or a loop-shaped one, that sends and receives radio waves.", "x": "HF: 17.6 m dipole assemblies perpendicular to the arrays; VHF: 2.76 m folded dipoles, inner and outer on each array.", "src": "B24, NASA"},
  iceshell: {"t": "Ice shell", "m": ["ice shell", "ice-shell"], "d": "Europa's outer layer of ice, floating on the ocean. How thick it is, nobody knows yet.", "x": "Thickness is a REASON and ECM science goal; the site's slider is a what-if.", "src": "NASA"},
  ocean: {"t": "Subsurface ocean", "m": ["ocean"], "d": "The salty water scientists think lies under Europa's ice.", "x": "Its existence, depth and salinity are ECM goals; k₂ from G&RS is an independent diagnostic.", "src": "NASA, M23"},
  lineae: {"t": "Lineae", "m": ["lineae", "cracks?"], "d": "The long reddish cracks that criss-cross Europa's ice.", "x": "Drawn procedurally here for looks; no geological claim.", "src": "—"},
  ecm: {"t": "ECM (magnetometer)", "m": ["ECM", "magnetometer"], "d": "Europa Clipper Magnetometer: three tiny compasses on a long pole that feel magnetic fields.", "x": "Three triaxial fluxgates (FG1–3) at 8.5, 6.8, 5.2 m on an 8.5 m boom; boom axis ≈ (0, −0.94, −0.34); deployed 5 Nov 2024.", "src": "Co25, FK, D"},
  boom: {"t": "Boom", "m": ["boom", "pole"], "d": "A long pole that holds a sensor far away from the ship.", "x": "8.5 m extendable boom on the propulsion module; keeps the sensors away from spacecraft fields.", "src": "Co25, NASA"},
  fluxgate: {"t": "Fluxgate magnetometer", "m": ["fluxgates?", "compass(?:es)?"], "d": "A very sensitive electronic compass that measures a magnetic field in three directions.", "x": "Triaxial fluxgate sensors FG1, FG2, FG3.", "src": "Co25"},
  induced: {"t": "Induced magnetic field", "m": ["induced(?: magnetic)? field", "induction"], "d": "When a magnetic field changes around a conductor, like salty water, the conductor makes its own field in reply.", "x": "A time-varying primary field drives currents in a conducting shell; the secondary field's amplitude and phase constrain conductivity and depth. PIMS separates plasma effects from it.", "src": "NASA"},
  plasma: {"t": "Plasma", "m": ["plasma"], "d": "Gas so hot its atoms are broken into charged pieces. Space around Jupiter is full of it.", "x": "Measured by PIMS Faraday cups to separate plasma-induced field distortions from Europa's induced field.", "src": "NASA"},
  pims: {"t": "PIMS", "m": ["PIMS"], "d": "Plasma Instrument for Magnetic Sounding: four metal cups that catch plasma and measure it.", "x": "Two sensors (Upper, Lower), each with two orthogonal 90°-FOV Faraday cups: Upper RAM (+Z) and ANTI-NADIR (−Y), Lower NADIR (+Y) and ANTI-RAM (−Z); Lower on the propulsion module.", "src": "P24, FK"},
  faraday: {"t": "Faraday cup", "m": ["Faraday cups?"], "d": "A metal cup that catches charged particles and measures the tiny current they make.", "x": "General: a collector behind grids measuring current vs retarding potential. On PIMS: 90° FOV each.", "src": "P24, general"},
  maspex: {"t": "MASPEX", "m": ["MASPEX"], "d": "MAss SPectrometer for Planetary EXploration: it swallows gas and weighs each molecule.", "x": "Multi-bounce time-of-flight mass spectrometer, 1–500 m/z, resolving power > 25,000; inlet along +Z; built by SwRI.", "src": "W24, FK, NASA"},
  suda: {"t": "SUDA", "m": ["SUDA"], "d": "SUrface Dust Analyzer: it catches dust grains knocked off Europa and reads what they are made of.", "x": "Reflectron-type impact TOF mass spectrometer; boresight +Z, required ≤ 2.5° from Kepler ram at C/A on ≥ 90 % of flybys; impacts at 4–5 km/s.", "src": "K25, D"},
  massspec: {"t": "Mass spectrometer", "m": ["mass spectrometers?", "weighs? each molecule"], "d": "An instrument that sorts atoms and molecules by weight.", "x": "MASPEX (gas, multi-bounce TOF) and SUDA (dust impact, reflectron TOF).", "src": "W24, K25"},
  tof: {"t": "Time of flight", "m": ["time[- ]of[- ]flight", "TOF"], "d": "Heavy things fly slower: time how long a charged particle takes to cross a tube and you know its weight.", "x": "MBTOF for MASPEX; reflectron TOF for SUDA.", "src": "W24, K25"},
  eis: {"t": "EIS", "m": ["EIS", "NAC", "WAC"], "d": "Europa Imaging System: two cameras, a zoom (NAC) and a wide (WAC).", "x": "NAC 2.3° × 1.2°, 10 µrad IFOV, 0.5 m/px at 50 km, 2-axis gimbal ±30°; WAC 48° × 24°, 218 µrad, 11 m/px over a 44 km swath at 50 km; 4k × 2k detectors.", "src": "T24"},
  ethemis: {"t": "E-THEMIS", "m": ["E-THEMIS", "ETHEMIS"], "d": "Europa Thermal Emission Imaging System: a heat camera that looks for warm spots in the ice.", "x": "Three bands, 7–14, 14–28 and 28–80 µm; sensor assembly on the nadir deck; built by Arizona State University.", "src": "Ch24"},
  uvs: {"t": "Europa-UVS", "m": ["UVS"], "d": "Europa Ultraviolet Spectrograph: sees ultraviolet light to study thin gas above the ice.", "x": "55–206 nm; airglow port, high-resolution port and a solar port 40° off the main boresight; FOV offset ∼0.6° toward +Z; built at SwRI.", "src": "R24, P24"},
  mise: {"t": "MISE", "m": ["MISE"], "d": "Mapping Imaging Spectrometer for Europa: splits light into colours to tell ice from salts.", "x": "0.8–5 µm at 10 nm resolution; 25 m/px at 100 km; 300 cross-track pixels; scan mirror; mounts directly to the vault.", "src": "Bl24, P24"},
  aperture: {"t": "Aperture", "m": ["apertures?"], "d": "The opening an instrument looks through. On the mug, four apertures face +Y.", "x": "UVS, EIS NAC/WAC, MISE and E-THEMIS all have +Y apertures.", "src": "P24"},
  fov: {"t": "Field of view (FOV)", "m": ["field of view", "FOV", "footprints?"], "d": "How wide a camera sees, and the patch of ground that covers.", "x": "Angular FOV × range = ground footprint; NAC 2 km swath and WAC 44 km swath at 50 km.", "src": "T24"},
  gimbal: {"t": "Gimbal", "m": ["gimbal(?:led|s)?"], "d": "A motorised mount that lets a camera swivel without turning the whole ship.", "x": "NAC 2-axis gimbal, ±30° cross- and along-track (FK frames NAC CTG, ATG).", "src": "T24, FK"},
  spectrometer: {"t": "Spectrometer / spectrograph", "m": ["spectrometer", "spectrograph", "splits light"], "d": "An instrument that spreads light into its colours to identify materials.", "x": "MISE (0.8–5 µm), UVS (55–206 nm), E-THEMIS (thermal infrared).", "src": "Bl24, R24, Ch24"},
  hga: {"t": "HGA", "m": ["HGA", "high-gain antenna", "big dish", "dish"], "d": "High-gain antenna: the 3-metre dish that sends data to Earth. It points −Y.", "x": "Fixed 3 m X/Ka-band dish on −Y; X-band uplink, X and Ka downlink up to 16 kb/s and 500 kb/s; sunshade during inner cruise.", "src": "P24, M23, S25"},
  mga: {"t": "MGA", "m": ["MGA", "medium-gain antenna"], "d": "Medium-gain antenna: a smaller dish-like antenna that also points −Y.", "x": "X-band, −Y boresight; can be used for gravity science.", "src": "M23, P24"},
  lga: {"t": "LGA", "m": ["LGAs?", "low-gain antennas?"], "d": "Low-gain antenna: a small antenna that hears in almost every direction but only slowly.", "x": "Three X-band LGAs mounted in +Y, −Y and −Z; all-sky coverage, limited beyond near-Earth; numbering 1/2/3 unconfirmed (mug: 1 = +Y, 2 = −Y, 3 = −Z).", "src": "M23, P24, FK"},
  fba: {"t": "FBA", "m": ["FBAs?", "fan-beam antennas?", "fan beams?"], "d": "Fan-beam antenna: an antenna whose beam is wide one way and thin the other, like light through a letterbox.", "x": "Three X-band FBAs in the Y/Z plane, narrow axis along X, for carrier-only Doppler during encounters; FBA1 = −Y+Z, FBA2 = −Y−Z, FBA3 = +Y−Z.", "src": "M23, FK"},
  grs: {"t": "G&RS", "m": ["G&amp;RS", "G&RS", "gravity and radio science", "gravity science"], "d": "Gravity and Radio Science: measuring Europa's gravity from the wobble in the ship's radio tone.", "x": "Primary measurement: tidal Love number k₂; two-way X-band Doppler from DSN 70 m stations ±2 h around C/A; any of 3 FBAs, 2 LGAs and the MGA.", "src": "M23, P24"},
  doppler: {"t": "Doppler", "m": ["Doppler"], "d": "The change in pitch of a wave when its source moves toward you or away from you, like a passing siren.", "x": "Two-way X-band carrier Doppler gives line-of-sight velocity; its perturbations map the gravity field.", "src": "M23"},
  k2: {"t": "Love number k₂", "m": ["k₂", "k2", "Love number"], "d": "A number that says how much a moon squishes under tides. A liquid ocean squishes a lot more than solid rock.", "x": "The gravitational tidal Love number k₂ is the primary G&RS measurement and an independent diagnostic of a global subsurface ocean.", "src": "M23"},
  dsn: {"t": "Deep Space Network (DSN)", "m": ["DSN", "Deep Space Network"], "d": "NASA's giant dish antennas on Earth that talk to spacecraft.", "x": "70 m stations used for gravity-science Doppler.", "src": "M23"},
  earthpoint: {"t": "Earth-point", "m": ["Earth-point(?:ing)?", "Earth point"], "d": "The pose where the dish (−Y) faces Earth to send data.", "x": "Normal downlink attitude; resumed about half a day after each C/A.", "src": "M23, C25"},
  sunpoint: {"t": "Sun-point", "m": ["Sun-point(?:ed|ing)?", "sunshade"], "d": "The pose where the dish faces the Sun and shades the ship, used only near the Sun.", "x": "Inner-cruise thermal attitude; the ECM boom then points at the Sun.", "src": "S25, Co25"},
  attitude: {"t": "Attitude", "m": ["attitude", "pose"], "d": "Which way the whole ship is facing.", "x": "Orientation of the body frame relative to inertial space; set by the wheels, sensed by SRUs and DSS.", "src": "general"},
  rwa: {"t": "RWA (reaction wheel)", "m": ["RWAs?", "reaction wheels?", "wheels?"], "d": "A heavy spinning wheel inside the ship. Spin it one way and the ship turns the other way, with no fuel.", "x": "Four Honeywell HR18-250 RWAs on D-Strut isolators, any three sufficient; two-foot wheels of steel, aluminium and titanium; on the propulsion module; positions and numbering unconfirmed.", "src": "S25, NASA, P24"},
  momentum: {"t": "Angular momentum", "m": ["angular momentum", "momentum"], "d": "The \"amount of spin\" something has. It cannot appear or vanish, only move between the wheels and the ship.", "x": "Conserved: wheel momentum change = −body momentum change; external torques accumulate until unloaded.", "src": "general"},
  rem: {"t": "REM", "m": ["REMs?", "rocket engine modules?"], "d": "Rocket Engine Module: a cluster of six small rocket engines. There are four clusters.", "x": "4 × 6 engines of 27.5 N; 16 point −Z in two sets of eight, 8 point ±Y in coupled pairs for roll; up to 8 at once for 220 N.", "src": "S25, P24, JPL"},
  thruster: {"t": "Thruster / engine", "m": ["thrusters?", "engines?", "nozzles?"], "d": "A small rocket that gives the ship a push.", "x": "27.5 N each; bipropellant MMH / MON-3.", "src": "S25, P24"},
  newton: {"t": "Newton (N)", "m": ["[Nn]ewtons?", "\\bN\\b"], "d": "The unit of push. One newton is about the weight of an apple; 27.5 N is about the weight of a 3-litre bottle of water.", "x": "SI unit of force; 220 N maximum with eight engines.", "src": "JPL", "cs": 1},
  biprop: {"t": "Bipropellant", "m": ["bipropellant", "propellant", "fuel"], "d": "A rocket fuel in two parts, a fuel and an oxidiser, that burn when they meet.", "x": "Monomethylhydrazine with mixed oxides of nitrogen (3 %) / nitrogen tetroxide; about 2,750 kg at launch.", "src": "P24, JPL"},
  sru: {"t": "SRU (star tracker)", "m": ["SRUs?", "star trackers?", "stellar reference units?"], "d": "A small camera that photographs stars and matches them to a map to tell the ship which way it faces.", "x": "Two Sodern HYDRA-derived units; boresights ≈ (±0.51, −0.34, +0.79) [D]; first images 4 Dec 2024; mounting location unconfirmed.", "src": "NASA, S25, FK"},
  dss: {"t": "DSS (Sun sensor)", "m": ["DSS", "(?:digital )?Sun sensors?"], "d": "A simple sensor that reports where the Sun is.", "x": "Adcole digital Sun sensors; two heads, DSS+Y ≈ (0, 0.99, −0.15) and DSS−Y ≈ (0, −0.91, +0.42) [D].", "src": "S25, FK"},
  boresight: {"t": "Boresight", "m": ["boresights?"], "d": "The exact direction an instrument or antenna points, its \"line of sight\".", "x": "Unit vector of the instrument frame's pointing axis in the body frame; most values here are derived from FK TKFRAME angles.", "src": "FK, D"},
  spice: {"t": "SPICE frames kernel", "m": ["SPICE", "frames kernel", "FK"], "d": "NASA's standard file that lists the named frames of a spacecraft and its instruments and which way each one points.", "x": "NAIF `clipper_v17.tf` (v1.7, 6 May 2026) defines EUROPAM_* frames and TKFRAME angles.", "src": "FK"},
  radiation: {"t": "Radiation dose", "m": ["radiation", "Mrad", "dose"], "d": "Jupiter's invisible high-energy particles that slowly damage electronics.", "x": "Tour design limit 3 Mrad TID behind 100 mil Al; planned tour 2.97 Mrad; per-flyby dose unconfirmed.", "src": "P24, C25"},
  rule: {"t": "Flight rule", "m": ["flight rules?", "FR"], "d": "A written safety rule that every command is checked against before it is sent to the ship.", "x": "English-prose constraints enforced by review or automated checkers (RP-check); rules carry a rationale, affected commands, criticality and enforcement.", "src": "RP-check, PDS"},
  lrr: {"t": "LRR", "m": ["LRR"], "d": "Limited Release Record: a JPL internal document type. The number on the mug is a record number, like a library card number.", "x": "Per {{OWNER}}: LRR = Limited Release Record, 095050 its record number; contents not public, not described here. Not the Launch Readiness Review (13 Oct 2024).", "src": "{{OWNER}}, NASA"},
  asteroid: {"t": "2026 DD", "m": ["2026 DD"], "d": "An asteroid that passes near Earth, first seen in February 2026. The mug's rule number may be a wink at it.", "x": "Apollo-class NEO, not a PHA; a = 2.29 au, e = 0.653, i = 25.4°; observed 2026-02-14 to 02-27 (JPL SBDB). Link to the mug: unconfirmed.", "src": "SBDB"},
  qr: {"t": "QR code", "m": ["QR codes?", "QR"], "d": "A square barcode a phone camera can read; this one opens the lid and coaster download.", "x": "Regenerated at build time for https://www.thingiverse.com/thing:7387069 and verified to scan.", "src": "BRIEF"},
  ccbysa: {"t": "CC BY-SA", "m": ["CC BY-SA"], "d": "A licence that lets anyone share and remix a design as long as they credit the maker and share alike.", "x": "Creative Commons Attribution-ShareAlike; applies to the ddThingz lid and coaster.", "src": "Thingiverse"},
  stl: {"t": "STL file", "m": ["STL"], "d": "A file format for 3D-printable shapes.", "x": "ecMugLid+Coaster.stl.", "src": "Thingiverse"},
  ganymede: {"t": "Ganymede and Callisto", "m": ["Ganymede", "Callisto"], "d": "Two more big moons of Jupiter that Clipper also flies past. Ganymede is where Clipper ends its life in 2034.", "x": "7 Ganymede and 9 Callisto flybys; disposal by Ganymede impact on 3 Sep 2034.", "src": "JPL, C25"},
  mrad: {"t": "TID", "m": ["total ionizing dose", "TID"], "d": "The running total of radiation damage.", "x": "Measured in rad; mission limit 3 Mrad behind 100 mil Al.", "src": "P24"},
  zeroposition: {"t": "Array zero position", "m": ["zero position"], "d": "The wing angle where the cells face the dish side (−Y).", "x": "SA_BASE +Z co-aligned with −Y; −90° is the SCA position.", "src": "FK, C25"},
  unconfirmed: {"t": "Unconfirmed", "m": ["unconfirmed"], "d": "We looked and found no public source for this, so we say so instead of guessing.", "x": "Items listed in fact sheet §6: LGA numbering, REM/RWA numbering and positions, SRU spots, \"−Y edge of vault\", PV sign in SCA, exact flyby speed, dose per flyby, Earth flyby date, FR/LRR meanings.", "src": "fact sheet"},
  mugmap: {"t": "\"As the mug shows\"", "m": ["as the mug shows"], "d": "This detail comes only from the mug, not from a published source.", "x": "Used for REM/RWA numbering and corners, LGA numbering, SRU and PIMS placement within a face, MASPEX/SUDA X positions.", "src": "print"},
  hf: {"t": "HF (high frequency)", "m": ["=\\bHF\\b"], "d": "Radio waves of a few million cycles a second. REASON's low note, 9 MHz, is HF: it goes deep into the ice.", "x": "General term: 3–30 MHz. On REASON the HF band is 9 MHz, radiated by two 17.6 m dipole assemblies on the solar arrays.", "src": "general term, B24"},
  vhf: {"t": "VHF (very high frequency)", "m": ["=\\bVHF\\b"], "d": "Radio waves of tens of millions of cycles a second. REASON's high note, 60 MHz, is VHF.", "x": "General term: 30–300 MHz. On REASON the VHF band is 60 MHz, radiated by four 2.76 m folded dipoles, inner and outer on each array.", "src": "general term, B24"},
  ifov: {"t": "IFOV (instantaneous field of view)", "m": ["IFOV"], "d": "The sliver of ground one single camera pixel sees. A tiny IFOV means sharp pictures.", "x": "General term: the angle subtended by one detector pixel; ground pixel ≈ IFOV × range. EIS NAC 10 µrad → 0.5 m at 50 km; WAC 218 µrad → 11 m at 50 km.", "src": "general term, T24"},
  fwhm: {"t": "FWHM (full width at half maximum)", "m": ["FWHM"], "d": "A standard way to say how thin a peak is: its width measured halfway up. Used to state how finely MASPEX separates masses.", "x": "General term: the width of a peak at half its height. MASPEX's resolving power above 25,000 is quoted on an FWHM basis.", "src": "general term, W24"},
  mbtof: {"t": "MBTOF (multi-bounce time of flight)", "m": ["MBTOF", "multi-bounce"], "d": "MASPEX's trick: it bounces ions back and forth many times so they fly a long way inside a short tube, which sorts their weights more finely.", "x": "\"Multi-bounce time-of-flight mass spectrometer (MBTOF)\": the MASPEX analyser type; 1–500 m/z, resolving power over 25,000 (FWHM).", "src": "W24"},
  fg: {"t": "FG1, FG2, FG3 (fluxgate sensors)", "m": ["FG[123]", "FG1[–-]3", "FG1[–-]FG3"], "d": "The three compass sensors on the magnetometer boom, numbered from the tip: FG1 is farthest out.", "x": "The three triaxial fluxgate magnetometers of ECM, \"mounted on a 8.5-m long extendable boom at distances of 8.5-m, 6.8-m, and 5.2-m, respectively\".", "src": "Co25"},
  st12: {"t": "ST1 / ST2 (star-tracker frames)", "m": ["=ST[12]", "=ST1/ST2"], "d": "The names the pointing files give the two star trackers. ST1 and ST2 are the same two SRUs the mug draws as blue barrels.", "x": "SPICE FK frame names for the two SRUs, in a \"56/52 configuration\"; ST2 was \"rotated 199 deg about the ST2 boresight\" to match the as-installed state. Boresights [D] ≈ (±0.51, −0.34, +0.79).", "src": "FK, D"},
  ck: {"t": "CK frame", "m": ["=\\bCK\\b", "C-kernel"], "d": "A part of the spacecraft that can move, like a solar wing, so its direction has to be read from a time log rather than a fixed number.", "x": "SPICE \"C-kernel\" frame: orientation given by a time-tagged pointing file rather than fixed angles. The solar-array frames EUROPAM_SA+X and SA−X are CK frames because each array has one degree of freedom.", "src": "general term (NAIF), FK"},
  eom: {"t": "EOM (end of mission)", "m": ["=\\bEOM\\b", "end of mission"], "d": "The end of the planned mission, when the parts have aged the most; engineers quote the worst-case numbers for then.", "x": "End of (prime) mission, 23 June 2034. Design figures quoted at EOM: 700 W solar-array power and 365 Ah battery capacity.", "src": "P24"},
  lv: {"t": "LV (launch vehicle)", "m": ["=\\bLV\\b", "launch vehicle"], "d": "The rocket. Clipper's was a Falcon Heavy. The ship's Z axis runs along the rocket's centreline.", "x": "Launch vehicle: a fully expendable SpaceX Falcon Heavy, LC-39A, 14 Oct 2024. The body frame's X–Y plane is the spacecraft–LV separation interface and +Z is \"nominally parallel to the launch vehicle centerline\".", "src": "C25, NASA, FK"},
  pha: {"t": "PHA (potentially hazardous asteroid)", "m": ["=\\bPHA\\b", "potentially hazardous"], "d": "A label for asteroids big enough and passing close enough that astronomers keep a special eye on them. 2026 DD is not one.", "x": "General term (JPL/CNEOS classification by minimum orbit-intersection distance and size). JPL's Small-Body Database lists (2026 DD) as an Apollo-class NEO that is not a PHA.", "src": "general term, SBDB"},
  icemag: {"t": "ICEMAG", "m": ["ICEMAG"], "d": "The magnetometer's old name. It was renamed ECM.", "x": "Former name of the Europa Clipper Magnetometer; the FK renamed the ICEMAG frames to ECM in v1.4 (2020). (The expansion \"Interior Characterization of Europa using Magnetometry\" is general knowledge, not in the fact sheet, and is unconfirmed.)", "src": "FK"},
  hydra: {"t": "HYDRA", "m": ["HYDRA"], "d": "The off-the-shelf star-tracker family Clipper's two trackers were adapted from.", "x": "Sodern's star-tracker product line; Clipper's SRUs are \"a specially modified version of their standard HYDRA product line\".", "src": "S25"},
};
for (const T of Object.values(TERMS)) for (const f of ['d', 'x', 'src']) T[f] = T[f].replaceAll('{{OWNER}}', OWNER_NAME);

/* ── link terms inside a container (first occurrence per block) ── */
const SKIP = new Set(['H1', 'H2', 'H3', 'H4', 'H5', 'BUTTON', 'LABEL', 'OUTPUT', 'SVG', 'TEXT', 'A', 'TH', 'INPUT', 'CODE']);
const SKIPC = ['eq', 'term', 'kicker', 'nolink', 'src', 'pophead'];
let RX = null;
function build() {
  const alts = [];
  for (const k in TERMS) for (const m of TERMS[k].m) { const cs = m[0] === '='; alts.push([cs ? m.slice(1) : m, k, cs || !!TERMS[k].cs]); }
  alts.sort((a, b) => b[0].length - a[0].length);
  RX = { re: new RegExp('(?<![\\w-])(' + alts.map((a) => a[0]).join('|') + ')(?![\\w-])', 'i'), alts: alts.map(([m, k, cs]) => [new RegExp('^(?:' + m + ')$', cs ? '' : 'i'), k]) };
}
const BLOCKS = 'p, li, td, figcaption, summary, .cards3 > div > span, .ge > p';
export function autoLink(root) {
  if (!RX) build();
  if (!root) return;
  const blocks = [...(root.matches && root.matches(BLOCKS) ? [root] : []), ...root.querySelectorAll(BLOCKS)];
  for (const b of blocks) {
    // every paragraph links its own jargon, so a dotted definition is never far away
    const seen = new Set([...b.querySelectorAll('.term')].map((t) => t.dataset.t));
    const walker = document.createTreeWalker(b, NodeFilter.SHOW_TEXT, {
      acceptNode(n) {
        for (let e = n.parentElement; e && e !== b.parentElement; e = e.parentElement) {
          if (SKIP.has(e.tagName.toUpperCase()) || SKIPC.some((c) => e.classList.contains(c))) return NodeFilter.FILTER_REJECT;
        }
        return NodeFilter.FILTER_ACCEPT;
      },
    });
    const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const node of nodes) {
      const text = node.nodeValue; let m, frag = null, last = 0;
      const re = new RegExp(RX.re.source, 'gi');
      while ((m = re.exec(text))) {
        const word = m[1];
        const hit = RX.alts.find(([r]) => r.test(word));
        if (!hit) continue;
        const key = hit[1];
        if (seen.has(key)) continue;
        seen.add(key);
        frag ||= document.createDocumentFragment();
        frag.append(text.slice(last, m.index));
        const btn = document.createElement('button');
        btn.type = 'button'; btn.className = 'term'; btn.dataset.t = key; btn.textContent = word;
        frag.append(btn);
        last = m.index + word.length;
      }
      if (frag) { frag.append(text.slice(last)); node.replaceWith(frag); }
    }
  }
}
